---
ID: "48d250cc-abed-4fc0-baad-0217654c50fe"
Parent: "d825a6a9-1510-4f33-9994-2f5df8b99f10"
Template: "fd2059fd-6043-4dfe-8c04-e2437ce87634"
Path: /sitecore/content/Skate Park/Skate Park/Presentation/Partial Designs/Product Content
SharedFields:
- ID: "55faae90-3bba-4f7f-96fe-13c3f40055ff"
  Hint: Signature
  Value: "product-content"
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{94DEA3A6-7088-4A66-AB3F-7EB63438C5B1}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{A2F9DC6F-ECA4-47BE-86DF-8844D67EE843}"
              p:before="*"
              s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;BackgroundImage&amp;Styles=%7C%7BEAE0C98E-D4DD-412E-AC8C-82A3D6DBDCB0%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main" />
            <r
              uid="{BBA13CC4-6815-4588-9248-2F5467F5AB7B}"
              p:after="r[@uid='{A2F9DC6F-ECA4-47BE-86DF-8844D67EE843}']"
              s:id="{3836D951-BB14-43AC-9231-649B7F245DC5}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7BEA0DE2E8-A6B0-49F2-A498-28492CF29832%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
              s:ph="/headless-main/container-1" />
            <r
              uid="{BBF74A42-BD04-4DF4-A182-140D0241D6F9}"
              p:after="r[@uid='{BBA13CC4-6815-4588-9248-2F5467F5AB7B}']"
              s:id="{C5F905F8-FD1F-444E-A9E5-AC6B774FF0DE}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B12581D42-EB43-47C1-9E81-18423472FC99%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=3"
              s:ph="/headless-main/container-1" />
            <r
              uid="{71CA4FF4-944F-457E-A726-ED3E272F008A}"
              p:after="*[1=2]"
              s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;BackgroundImage&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=4"
              s:ph="/headless-main/container-1" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240404T201013Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sean.carter@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sean.carter@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "254c7079-2d8e-46fd-accd-062d46048fb6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sean.carter@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240405T120359Z
